export type EventType = 'entitycreate'
| 'entityupdate'
| 'entityclone'
| 'entityselect'
| 'cameraperspectivetoggle'
| 'cameraorthographictoggle'
| 'objectselect'
| 'objectfocus'
| 'objectremove'
| 'helperremove'
| 'raycastermouseenter'
| 'raycastermouseleave'
| 'inspectortoggle'
| 'transformmodechange'
| 'transformspacechange'
| 'transformspacechanged'
| 'cameraperspectivetoggle'
| 'cameraorthographictoggle'
| 'cameratoggle'
| 'entitytransformed'
| 'refreshsidebarobject3d'
;
