export type EventType = 'entitycreate'
| 'entityupdate'
| 'entityclone'
| 'entityselect'
| 'cameraperspectivetoggle'
| 'cameraorthographictoggle'
| 'objectselect'
| 'objectfocus'
| 'objectremove'
| 'helperremove'
;
